import type { EmailTemplate } from '@/types/emailTemplate'

export const DEFAULT_EMAIL_TEMPLATES: EmailTemplate[] = [
  {
    id: 'order_confirmation',
    name: 'Order Confirmation (Customer)',
    category: 'Orders',
    enabled: true,
    subject: '🍕 Order Confirmed #{{orderId}} - {{businessName}}',
    heading: '🍕 Your Wood-Fired Pizza is Confirmed!',
    subheading: 'Order #{{orderId}} • Preparing Fresh in Allapur',
    bodyText:
      'Hi {{customerName}}, thank you for your order! Our wood-fired kitchen in Allapur has accepted your order and started preparing your fresh artisanal pizzas with 48-hour fermented dough and authentic San Marzano sauce.',
    buttonText: 'Track Live Order Status',
    buttonUrl: '{{trackingUrl}}',
    footerNote:
      'Questions about your order? Call our store at {{storePhone}} or message us on WhatsApp.',
    bannerColor: '#B91C1C',
    variables: [
      '{{customerName}}',
      '{{orderId}}',
      '{{total}}',
      '{{itemsTable}}',
      '{{deliveryAddress}}',
      '{{paymentMethod}}',
      '{{trackingUrl}}',
      '{{businessName}}',
      '{{storePhone}}',
    ],
  },
  {
    id: 'admin_order_alert',
    name: 'Instant Order Alert (Store Owner & Kitchen)',
    category: 'Alerts',
    enabled: true,
    subject: '🚨 NEW ORDER #{{orderId}} Received (₹{{total}})',
    heading: '🚨 NEW CUSTOMER ORDER RECEIVED!',
    subheading: 'Order #{{orderId}} • Immediate Preparation Required',
    bodyText:
      'A new online delivery order has been placed by {{customerName}} ({{customerPhone}}). Destination: {{deliveryAddress}}. Payment: {{paymentMethod}}.',
    buttonText: 'Open Kitchen Display System (KDS)',
    buttonUrl: '{{adminKdsUrl}}',
    footerNote:
      'Pizza Expert Real-Time POS & Automated Dispatch Alert System',
    bannerColor: '#FF3B00',
    variables: [
      '{{customerName}}',
      '{{customerPhone}}',
      '{{orderId}}',
      '{{total}}',
      '{{itemsTable}}',
      '{{deliveryAddress}}',
      '{{paymentMethod}}',
      '{{adminKdsUrl}}',
    ],
  },
  {
    id: 'out_for_delivery',
    name: 'Out for Delivery / Dispatched (Customer)',
    category: 'Delivery',
    enabled: true,
    subject: '🛵 Your Pizza is On The Way! #{{orderId}}',
    heading: '🛵 Your Rider is Heading to Your Doorstep!',
    subheading: 'Hot & Fresh • Wood-Fired to Table',
    bodyText:
      'Hi {{customerName}}, great news! Your delivery partner {{driverName}} ({{driverPhone}}) has picked up your piping-hot order and is speeding over to {{deliveryAddress}}. Please keep verification OTP {{deliveryOtp}} handy.',
    buttonText: 'Track Live Rider GPS',
    buttonUrl: '{{trackingUrl}}',
    footerNote:
      'Please share OTP {{deliveryOtp}} with the rider upon doorstep delivery for contactless verification.',
    bannerColor: '#9333EA',
    variables: [
      '{{customerName}}',
      '{{orderId}}',
      '{{driverName}}',
      '{{driverPhone}}',
      '{{deliveryOtp}}',
      '{{deliveryAddress}}',
      '{{trackingUrl}}',
      '{{businessName}}',
    ],
  },
  {
    id: 'order_delivered',
    name: 'Delivered & Review Request (Customer)',
    category: 'Delivery',
    enabled: true,
    subject: '⭐ How was your pizza? Order #{{orderId}}',
    heading: '⭐ Order Delivered! Enjoy Every Bite!',
    subheading: 'Order #{{orderId}} • Tell us how we did',
    bodyText:
      'Hi {{customerName}}, your order #{{orderId}} has been successfully delivered. We hope every slice was hot, cheesy, and crispy! Please take 15 seconds to rate your experience.',
    buttonText: 'Rate Order & Leave Review',
    buttonUrl: '{{reviewUrl}}',
    footerNote:
      '5-Star reviews on Google earn you 50 bonus loyalty points on your next slice!',
    bannerColor: '#15803D',
    variables: [
      '{{customerName}}',
      '{{orderId}}',
      '{{total}}',
      '{{reviewUrl}}',
      '{{googleReviewUrl}}',
      '{{businessName}}',
    ],
  },
  {
    id: 'abandoned_cart',
    name: 'Abandoned Cart Recovery (Marketing)',
    category: 'Marketing',
    enabled: true,
    subject: '🍕 You left delicious pizzas in your cart! Here is 10% OFF',
    heading: '🍕 Still Craving Wood-Fired Pizza?',
    subheading: 'Your cart is saved • Use code PIZZA10 for 10% OFF',
    bodyText:
      'Hi {{customerName}}, we noticed you left some mouth-watering pizzas in your cart! We saved your custom toppings and selections. Complete your checkout now before our kitchen reaches daily capacity.',
    buttonText: 'Complete My Order (10% OFF)',
    buttonUrl: '{{checkoutUrl}}',
    footerNote:
      'Coupon code PIZZA10 is valid for the next 24 hours only.',
    bannerColor: '#D97706',
    variables: [
      '{{customerName}}',
      '{{cartItemsTable}}',
      '{{checkoutUrl}}',
      '{{discountCode}}',
      '{{businessName}}',
    ],
  },
  {
    id: 'order_cancelled',
    name: 'Order Cancellation & Refund Notice',
    category: 'Orders',
    enabled: true,
    subject: '⚠️ Order Cancelled #{{orderId}} - Refund Details',
    heading: '⚠️ Order Cancellation Notice',
    subheading: 'Order #{{orderId}} • Refund Details',
    bodyText:
      'Hi {{customerName}}, we regret to inform you that order #{{orderId}} has been cancelled. If you paid online via Razorpay/UPI, your refund of ₹{{total}} has been automatically initiated back to your original source (3-5 business days).',
    buttonText: 'Contact Store Support',
    buttonUrl: '{{contactUrl}}',
    footerNote:
      'We sincerely apologize for the inconvenience. Call us at {{storePhone}} for instant assistance.',
    bannerColor: '#DC2626',
    variables: [
      '{{customerName}}',
      '{{orderId}}',
      '{{total}}',
      '{{paymentMethod}}',
      '{{cancelReason}}',
      '{{contactUrl}}',
      '{{storePhone}}',
      '{{businessName}}',
    ],
  },
  {
    id: 'welcome_loyalty',
    name: 'Welcome VIP Member (Marketing)',
    category: 'Marketing',
    enabled: true,
    subject: '🎉 Welcome to {{businessName}} VIP Rewards Club!',
    heading: '🎉 Welcome to the Pizza Family!',
    subheading: 'You have received 100 Welcome Loyalty Points',
    bodyText:
      'Hi {{customerName}}, welcome to {{businessName}}! As a member, you earn rewards on every order, get secret coupon codes, and enjoy exclusive priority delivery perks across Prayagraj.',
    buttonText: 'Explore Delicious Menu',
    buttonUrl: '{{menuUrl}}',
    footerNote:
      'Show this email at our Allapur store for free garlic bread on your next dine-in visit!',
    bannerColor: '#FF3B00',
    variables: [
      '{{customerName}}',
      '{{loyaltyPoints}}',
      '{{menuUrl}}',
      '{{businessName}}',
    ],
  },
]

export const SAMPLE_TEMPLATE_VALUES: Record<string, string> = {
  '{{customerName}}': 'Rahul Sharma',
  '{{customerPhone}}': '+91 98765 43210',
  '{{orderId}}': 'ORD-982143',
  '{{total}}': '649.00',
  '{{itemsTable}}': '1x Farmhouse Supreme (Medium) • 1x Garlic Breadsticks • 1x Coke (500ml)',
  '{{cartItemsTable}}': '1x Pepperoni Feast Pizza • 1x Cheese Stuffed Garlic Bread',
  '{{deliveryAddress}}': 'Flat 302, Green Valley Apts, Civil Lines, Prayagraj 211001',
  '{{paymentMethod}}': 'Razorpay UPI (Paid)',
  '{{trackingUrl}}': 'https://pizza-kappa-nine.vercel.app/track?orderId=ORD-982143',
  '{{reviewUrl}}': 'https://pizza-kappa-nine.vercel.app/order/ORD-982143',
  '{{checkoutUrl}}': 'https://pizza-kappa-nine.vercel.app/checkout',
  '{{menuUrl}}': 'https://pizza-kappa-nine.vercel.app/menu',
  '{{contactUrl}}': 'https://pizza-kappa-nine.vercel.app/contact',
  '{{adminKdsUrl}}': 'https://pizza-kappa-nine.vercel.app/admin/kitchen',
  '{{googleReviewUrl}}': 'https://g.page/r/pizzaexpert-prayagraj/review',
  '{{driverName}}': 'Amit Kumar',
  '{{driverPhone}}': '+91 98111 22334',
  '{{deliveryOtp}}': '7842',
  '{{discountCode}}': 'PIZZA10',
  '{{loyaltyPoints}}': '100',
  '{{cancelReason}}': 'Out of delivery zone request',
  '{{businessName}}': 'Pizza Expert',
  '{{storePhone}}': '+91 91234 56789',
}
